<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Pages\Module'                        => __DIR__ . '/Module.php',
    'Pages\Controller\HomeController' => __DIR__ . '/src/Pages/Controller/HomeController.php',
    'PagesTest\Framework\TestCase'        => __DIR__ . '/tests/Pages/Framework/TestCase.php',
    'PagesTest\SampleTest'                => __DIR__ . '/tests/Pages/SampleTest.php',
);
