<div class="row-fluid homeHeader">
	<div class="span9">
		<div class="progress challenge">
    		<div class="bar" style="width: 70%;">
    			<span>&nbsp;Challenge&nbsp;progress:&nbsp;<span>70</span>%</span>
    		</div>
    	</div>
    </div>
	<div class="span3 row-fluid">
		<?php
			$location = $this->basePath() . '/pages/inscription/choice';
		?>
		<button onclick="window.location.href = '<?php echo $this->basePath()?>/pages/inscription/choice';" class="btn-primary span12 dareit">DARE-it</button>
	</div>
	<div class="span1"></div>
</div>
<div class="row-fluid">
	<div class="span9">
		<div class="row-fluid">
			<div class="span4 pageBlock primary">
				<h3>The Concept</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate, purus sit amet adipiscing laoreet, lectus lectus congue libero, nec posuere arcu lectus ac sapien. Donec non odio a mauris congue eleifend.</p>
			</div>
			<div class="span8 pageBlock">
				<h3>Testimonies</h3>
				<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate, purus sit amet adipiscing laoreet, lectus lectus congue libero, nec posuere arcu lectus ac sapien. Donec non odio a mauris congue eleifend. Integer elementum mi ut elit commodo mollis. Etiam molestie viverra urna eu pharetra. Curabitur porta felis massa, in dignissim augue dignissim luctus. Duis tincidunt leo sed metus blandit iaculis. Donec sed hendrerit urna. Maecenas semper purus leo, in rutrum enim bibendum eget. Proin in vehicula urna. Etiam eleifend tortor a metus consectetur, nec sagittis nisl aliquam.</p>
			</div>		
		</div>
		<div class="row-fluid">
			<div class="span4 pageBlock">
				<h3>Video Manual</h3>
				<iframe width="100%" height="150px" src="http://www.youtube.com/embed/AUoPvDX-KIc" frameborder="0" allowfullscreen></iframe>
			</div>
			<div class="span8 pageBlock">
				<h3>Latest offers and demands</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate, purus sit amet adipiscing laoreet, lectus lectus congue libero, nec posuere arcu lectus ac sapien. Donec non odio a mauris congue eleifend. Integer elementum mi ut elit commodo mollis. Etiam molestie viverra urna eu pharetra. Curabitur porta felis massa, in dignissim augue dignissim luctus. Duis tincidunt leo sed metus blandit iaculis. Donec sed hendrerit urna. Maecenas semper purus leo, in rutrum enim bibendum eget. Proin in vehicula urna. Etiam eleifend tortor a metus consectetur, nec sagittis nisl aliquam.</p>
			</div>			
		</div>
	</div>
	<div class="span3 pageBlock bold">		
		<iframe width="100%" height="150px" src="http://www.youtube.com/embed/0sUL0KCIc48" frameborder="0" allowfullscreen></iframe>
		<iframe width="100%" height="150px" src="http://www.youtube.com/embed/vzctcWJZ9DU" frameborder="0" allowfullscreen></iframe>
		<iframe width="100%" height="150px" src="http://www.youtube.com/embed/0Bmhjf0rKe8" frameborder="0" allowfullscreen></iframe>
	</div>
</div>
<div class="row-fluid">
	<div class="span4 pageBlock">
		<h3>[Calender and news]</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate, purus sit amet adipiscing laoreet, lectus lectus congue libero, nec posuere arcu lectus ac sapien. Donec non odio a mauris congue eleifend. Integer elementum mi ut elit commodo mollis. Etiam molestie viverra urna eu pharetra. Curabitur porta felis massa, in dignissim augue dignissim luctus. Duis tincidunt leo sed metus blandit iaculis. Donec sed hendrerit urna. Maecenas semper purus leo, in rutrum enim bibendum eget. Proin in vehicula urna. Etiam eleifend tortor a metus consectetur, nec sagittis nisl aliquam.	
	</div>
	<div class="span4 pageBlock">
		<h3>[Challenge map]</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate, purus sit amet adipiscing laoreet, lectus lectus congue libero, nec posuere arcu lectus ac sapien. Donec non odio a mauris congue eleifend. Integer elementum mi ut elit commodo mollis. Etiam molestie viverra urna eu pharetra. Curabitur porta felis massa, in dignissim augue dignissim luctus. Duis tincidunt leo sed metus blandit iaculis. Donec sed hendrerit urna. Maecenas semper purus leo, in rutrum enim bibendum eget. Proin in vehicula urna. Etiam eleifend tortor a metus consectetur, nec sagittis nisl aliquam.	
	</div>
		<div class="span4 pageBlock">
		<h3>[Download and share]</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate, purus sit amet adipiscing laoreet, lectus lectus congue libero, nec posuere arcu lectus ac sapien. Donec non odio a mauris congue eleifend. Integer elementum mi ut elit commodo mollis. Etiam molestie viverra urna eu pharetra. Curabitur porta felis massa, in dignissim augue dignissim luctus. Duis tincidunt leo sed metus blandit iaculis. Donec sed hendrerit urna. Maecenas semper purus leo, in rutrum enim bibendum eget. Proin in vehicula urna. Etiam eleifend tortor a metus consectetur, nec sagittis nisl aliquam.	
	</div>		
</div>
<div class="row-fluid">
	<div class="span12 pageBlock dark">
		<h3>Our partners</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate, purus sit amet adipiscing laoreet, lectus lectus congue libero, nec posuere arcu lectus ac sapien. Donec non odio a mauris congue eleifend. Integer elementum mi ut elit commodo mollis. Etiam molestie viverra urna eu pharetra. Curabitur porta felis massa, in dignissim augue dignissim luctus. Duis tincidunt leo sed metus blandit iaculis. Donec sed hendrerit urna. Maecenas semper purus leo, in rutrum enim bibendum eget. Proin in vehicula urna. Etiam eleifend tortor a metus consectetur, nec sagittis nisl aliquam.</p>		
	</div>
</div>
