<div class="row-fluid">
	<div class="span4"></div>
	<div class="span4 exclamation"><span>THANK YOU FOR DARING WITH US!!</span></div>
	<div class="span4"></div>
</div>

<div class="row-fluid">
	<div class="span3"></div>
	<div class="span2 inscriptionChoice"><span>If you want to participate as an indidual:</span></div>
	<div class="span2"></div>
	<div class="span2 inscriptionChoice">If you want to subscribe an organisation that will manage other profiles:</div>
	<div class="span3"></div>
</div>


<div class="row-fluid">
	<div class="span3"></div>
	<div class="span2"><a href="<?php echo $this->basePath()?>/pages/inscription/individual" class="btn-primary span12 dareit">Individual</a></div>
	<div class="span2"></div>
	<div class="span2"><a href="<?php echo $this->basePath()?>/pages/inscription/organisation" class="btn-primary span12 dareit">Organisation</a></div>
	<div class="span3"></div>
</div>
