<div class="row-fluid">
	<form>
		<div class="span4">
			<fieldset>
	    		<label>Name*</label>
		    	<input type="text">
		    	<label>First name*</label>
		    	<input type="text">
		    	<label>User name*</label>
		    	<input type="text">
		    	<label>E-mail*</label>
		    	<input type="text">   
		    	<label>Password*</label>
		    	<input type="text">   
		    	<label>Confirm password*</label>
		    	<input type="text">   		    	
    		</fieldset>   	    	
    	</div>
		<div class="span4">
			<fieldset>
	    		<label>Street and number*</label>
		    	<input type="text">
		    	<label>Postcode and city*</label>
		    	<input type="text">
		    	<label>Telephone</label>
		    	<input type="text">
		    	<label>Number ID card</label>
		    	<input type="text">   
		    	<label>Upload copy ID card</label>
		    	Browse  
		    	<label>Facebook page</label>
		    	<input type="text">   		    	
    		</fieldset>   	    	
    	</div>
    	<div class="span4"></div>    
	</form>
</div>